version: '3.5'
services:
  jenkins:
    build: .
    image: dmadk/jenkins
    container_name: jenkins
    ports:
      - "8087:8080"
      - "50007:50000"
    volumes:
      - ~/jenkins_home:/var/jenkins_home
#    restart: unless-stopped
