version: '3.5'
services:
  jenkins:
    build: .
    image: dmadk/jenkins
    container_name: jenkins
    ports:
      - "8087:8080"
      - "50007:50000"
    volumes:
      - type: bind
        source: ./jenkins_home
        target: /var/jenkins_home
#    restart: unless-stopped
